language: python

python: 2.7

cache: pip

addons:
  postgresql: "9.4"

env:
- DJANGO_SETTINGS_MODULE=reports.settings.travis

before_install:
  - git clone https://git.linaro.org/qa/manual-test-definitions.git ext/manual-test-definitions
  - psql -c 'create database "qa-reports";' -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py test --noinput -v 2
  - flake8 --select=F821,F823 . --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.virtualenv,ext


notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels: "chat.freenode.net#linaro-qa"
    template: "%{repository}@%{branch}: %{message} (%{build_url})"