# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 11:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_definitions', to='reports.Definition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.CharField(max_length=24)),
                ('dtb', models.CharField(max_length=256)),
                ('tree', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('kernel', models.CharField(max_length=256)),
                ('defconfig', models.CharField(max_length=256)),
                ('arch', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('executable', models.BooleanField(default=False)),
                ('submited', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestJob',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(max_length=128, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.RunDefinition')),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_jobs', to='reports.TestExecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=128, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('test_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_results', to='reports.TestJob')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='testexecution',
            unique_together=set([('build_id', 'dtb')]),
        ),
    ]
