# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='kind',
            field=models.CharField(default='manual', max_length=256),
            preserve_default=False,
        ),
    ]
