# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_definition_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='kind',
            field=models.CharField(choices=[(b'm', b'manual'), (b'a', b'automatic')], max_length=256),
        ),
    ]
