# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160225_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='definition',
            name='kind',
            field=models.CharField(choices=[(b'manual', b'manual'), (b'automatic', b'automatic')], max_length=256),
        ),
    ]
