# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160226_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='modifed_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 26, 10, 2, 58, 969369, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
