# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_testresult_modifed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
