# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='board',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='kind',
            field=models.CharField(choices=[(b'manual', b'manual'), (b'automatic', b'automatic'), (b'kernelci', b'kernelci')], max_length=256),
        ),
        migrations.AlterField(
            model_name='permission',
            name='field',
            field=models.CharField(max_length=256, validators=[reports.models.validate_field]),
        ),
    ]
