# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:45
from __future__ import unicode_literals

from django.db import migrations


def migrate(apps, schema_editor):
    Model = apps.get_model("reports", "TestExecution")

    for item in Model.objects.all():
        item.board = item.dtb.replace("dtbs/", "").replace(".dtb", "")
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20160303_1644'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
