# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20160303_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testexecution',
            unique_together=set([('build_id', 'board')]),
        ),
    ]
