# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20160303_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='dtb',
        ),
    ]
