# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_testexecution_dtb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='run_definition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.RunDefinition'),
        ),
    ]
