# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20160304_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='kind',
            field=models.CharField(default='', editable=False, max_length=256),
            preserve_default=False,
        ),
    ]
