# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20160304_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='testresult',
            name='regression',
            field=models.BooleanField(default=False),
        ),
    ]
