# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20160308_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='modifed_at',
            new_name='modified_at',
        ),
    ]
