# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
        migrations.AddField(
            model_name='issue',
            name='test_job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='reports.TestJob'),
            preserve_default=False,
        ),
    ]
