# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20160318_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='test_job',
        ),
        migrations.AddField(
            model_name='issue',
            name='test_result',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reports.TestResult'),
            preserve_default=False,
        ),
    ]
