# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20160321_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='remote_id',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='remote_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
