# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_issue_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('test_result', 'kind', 'number')]),
        ),
    ]
