# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20160325_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
