# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_testresult_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='note',
            new_name='notes',
        ),
    ]
