# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:45
from __future__ import unicode_literals

from django.db import migrations


def migrate(apps, schema_editor):
    TestResult = apps.get_model("reports", "TestResult")
    for test_result in TestResult.objects.all():
        if not test_result.status:
            test_result.modified_by = None
            test_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_auto_20160329_1407'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop),
    ]
