# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_auto_20160329_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='dtb',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
