# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_testexecution_dtb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testexecution',
            old_name='dtb',
            new_name='dtb_url',
        ),
        migrations.AddField(
            model_name='testexecution',
            name='image_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
